### ISSUE TITLE
add support for minimizing a container for particular commands

### ISSUE THREAD

**Issue by satra** [kaczmarj/neurodocker#23]
see https://github.com/freesurfer/freesurfer/issues/70 for creating a reprozip pack file.

**Comment by kaczmarj** [comment]
@satra - I have come up with a few ways of implementing this:

Run reprozip on some command(s) within the container, and ...

1. within the same container, delete all files except those listed in the reprozip trace file, and commit that container to save it as an image.
2. similar to above, but only delete files within the software installation directory (similar to what you did with freesurfer's recon-all in the linked issue).
3. save the reprozip pack file to the local machine, and create a new, minimized docker image with reprounzip-docker.

Which option do you think is best? Is there a better way of doing this?

**Comment by kaczmarj** [comment]
Quick update - it seems that `reprozip trace` cannot be used while building a docker image (at least on macOS; it should be possible on Linux). The `--security-opt seccomp:unconfined` option is not available on macOS. An implementation of ReproZip in neurodocker will probably have to build the image, run the container, run `reprozip trace` in that running container, and commit the minified image.

(Another implementation can save the reprozip pack file and create a new image with `reprounzip-docker`)

This is unfortunate because there is a `--squash` option in the `docker build` command, which squashes all of the layers into one, but that option is not available for containers. Some third party tools exist to fill that gap. It is important to squash the layers because any files deleted after running `reprozip trace` will still be present in previous layers, so there will be no difference in image size unless those layers are squashed into one.

Build command:

`docker build --security-opt seccomp:unconfined --squash -t mini-test - < dockerfile_tests/scratch/Dockerfile`

Error:

`Error response from daemon: the daemon on this platform does not support --security-opt to build`

**Comment by satra** [comment]
@kaczmarj - perhaps we can do it as a runtime option rather than build option. so build, run and trace with commands, create minimal container. this option `--security-opt seccomp:unconfined` definitely exists when running a container. my freesurfer trace was done on os x.
